import { mkdir, mkdtemp, cp, rm } from 'node:fs/promises';
import { join } from 'node:path';
import { tmpdir } from 'node:os';
import { DebComposeError, ErrorCode } from '../error/index.js';
import { generateManifest } from '../manifest/index.js';
import { checkDpkgDeb } from '../packager/index.js';
import { runBuildPipeline } from './pipeline.js';

/**
 * @typedef {Object} BuildOptions
 * @property {string} debDir        - Directory containing .deb files
 * @property {string} [outputDir]   - Output directory for the bundle .deb
 * @property {string} [version]     - Bundle version (default: 1.0.0)
 * @property {string} [package]     - Bundle package name (auto-detected from first .deb)
 * @property {string} [architecture] - Target architecture (default: amd64)
 * @property {string} [section]     - Package section (default: misc)
 * @property {string} [priority]    - Package priority (default: optional)
 * @property {string} [license]     - Package license
 * @property {string[]} [order]     - Custom package order
 * @property {string} [maintainer]  - Maintainer string
 * @property {string} [description] - Description string
 * @property {'stop' | 'rollback'} [onInstallError] - Behavior when a sub-package install fails (default: stop)
 */

/**
 * @typedef {Object} BuildResult
 * @property {string} outputPath       - Path to the generated .deb
 * @property {import('../manifest/schema.js').Manifest} manifest - Generated manifest
 * @property {boolean} dpkgDebAvailable - Whether dpkg-deb is available
 */

/**
 * Build a bundle .deb from a directory of sub-packages.
 *
 * @param {BuildOptions} options
 * @returns {Promise<BuildResult>}
 * @throws {DebComposeError} Any step in the pipeline
 */
export async function buildBundle(options) {
  const {
    debDir,
    outputDir,
    version,
    package: packageName,
    architecture,
    maintainer,
    description,
    section,
    priority,
    license,
    order,
    onInstallError,
  } = options;

  if (!debDir) {
    throw new DebComposeError(ErrorCode.INVALID_INPUT, 'debDir is required');
  }

  const dpkgDebAvailable = await checkDpkgDeb();
  if (!dpkgDebAvailable) {
    throw new DebComposeError(ErrorCode.BUILD_FAILED, 'dpkg-deb not found; install dpkg-dev first');
  }

  const manifest = await generateManifest(debDir, version || '1.0.0', order);

  const name = packageName || `${manifest.packages[0]?.name || 'bundle'}-installer`;

  const tmpDir = await mkdtemp(join(tmpdir(), 'debcompose-'));

  try {
    const bundleDir = join(tmpDir, 'opt', name);
    await mkdir(bundleDir, { recursive: true });
    await cp(debDir, bundleDir, { recursive: true });

    const { outputPath } = await runBuildPipeline({
      buildDir: tmpDir,
      manifest,
      controlConfig: {
        package: name,
        version: manifest.version,
        architecture: architecture || 'amd64',
        maintainer: maintainer || 'Unknown <unknown>',
        description: description || 'Bundle installer\n Auto-generated by debcompose.',
        section: section || 'misc',
        priority: priority || 'optional',
        license: license || undefined,
      },
      onInstallError,
    });

    // Move the output to the requested output directory
    const finalOutputPath = join(outputDir || process.cwd(), `${name}_${manifest.version}_${architecture || 'amd64'}.deb`);
    await mkdir(outputDir || process.cwd(), { recursive: true });
    await cp(outputPath, finalOutputPath);
    await rm(outputPath);

    return {
      outputPath: finalOutputPath,
      manifest,
      dpkgDebAvailable,
    };
  } finally {
    await rm(tmpDir, { recursive: true, force: true });
  }
}
