#!/usr/bin/env node

import fs from 'node:fs/promises';
import path from 'node:path';
import { buildBundle } from './builder/index.js';
import { ConsoleLogger } from './logger/index.js';

const logger = new ConsoleLogger(process.env.DEB_COMPOSE_LOG_LEVEL || 'info');

function showGlobalHelp() {
  console.log('\nDebCompose\nUsage:\n' +
    '  debcompose serve                       - Start the HTTP server\n' +
    '  debcompose build <dir> [options]      - Build a bundle from .deb directory\n' +
    '  debcompose <dir> [options]            - Build bundle (shortcut)\n\n' +
    'Commands:\n' +
    '  serve     Start web server for bundle debugging\n' +
    '  build     Build a deb bundle from directory of .deb files\n\n' +
    'Options (for build):\n' +
    '  -o, --output <dir>       Output directory (default: current directory)\n' +
    '  -v, --version <ver>      Bundle version (default: 1.0.0)\n' +
    '  -n, --name <name>        Package name (default: auto-detected)\n' +
    '      --arch <arch>        Target architecture (amd64, i386, arm64, armhf, etc.; default: amd64)\n' +
    '      --maintainer <str>   Maintainer field (default: "Unknown <unknown>")\n' +
    '      --description <str>  Description field (default: auto-generated)\n' +
    '      --section <str>      Package section (default: misc)\n' +
    '      --priority <str>     Package priority (optional, required, etc.; default: optional)\n' +
    '      --license <str>      License identifier (optional)\n\n' +
    'Control file format: https://www.debian.org/doc/debian-policy/ch-controlfields.html\n\n' +
    'Run \'debcompose build --help\' or \'debcompose --help\' for detailed options.\n');
}

function showBuildHelp() {
  console.log('\nDebCompose Build\nUsage:\n' +
    '  debcompose build <dir> [options]\n' +
    '  debcompose <dir> [options]\n\n' +
    'Options:\n' +
    '  -o, --output <dir>       Output directory (default: current directory)\n' +
    '  -v, --version <ver>      Bundle version (default: 1.0.0)\n' +
    '  -n, --name <name>        Package name (default: auto-detected)\n' +
    '      --arch <arch>        Target architecture (amd64, i386, arm64, armhf, etc.; default: amd64)\n' +
    '      --maintainer <str>   Maintainer field (default: "Unknown <unknown>")\n' +
    '      --description <str>  Description field (default: auto-generated)\n' +
    '      --section <str>      Package section (default: misc)\n' +
    '      --priority <str>     Package priority (optional, required, etc.; default: optional)\n' +
    '      --license <str>      License identifier (optional)\n' +
    '      --on-install-error   Error recovery strategy: stop or rollback (default: stop)\n' +
    '  -h, --help               Show this help message\n\n' +
    'Control file format: https://www.debian.org/doc/debian-policy/ch-controlfields.html\n\n' +
    'Examples:\n' +
    '  debcompose build ./packages\n' +
    '  debcompose build ./packages --output ./dist --version 2.0.0 --name my-app\n' +
    '  debcompose ./packages -o ./dist -v 1.2.0 -n my-product\n' +
    '  debcompose build ./packages --arch arm64 --section utils --priority optional\n' +
    '  debcompose build ./packages --on-install-error rollback\n');
}

function parseArgs(args) {
  const options = {
    dir: null,
    outputDir: process.cwd(),
    version: process.env.DEB_COMPOSE_VERSION || '1.0.0',
    packageName: process.env.DEB_COMPOSE_NAME || null,
    architecture: process.env.DEB_COMPOSE_ARCH || 'amd64',
    maintainer: process.env.DEB_COMPOSE_MAINTAINER || 'Unknown <unknown>',
    description: process.env.DEB_COMPOSE_DESCRIPTION || 'Bundle installer\n Auto-generated by debcompose.',
    section: process.env.DEB_COMPOSE_SECTION || 'misc',
    priority: process.env.DEB_COMPOSE_PRIORITY || 'optional',
    license: process.env.DEB_COMPOSE_LICENSE || '',
    onInstallError: process.env.DEB_COMPOSE_ON_INSTALL_ERROR || 'stop',
  };

  let i = 0;
  while (i < args.length) {
    const arg = args[i];
    
    if (arg === '--help' || arg === '-h') {
      options.help = true;
      break;
    }
    
    if (arg === '--output' || arg === '-o') {
      options.outputDir = args[++i];
    } else if (arg === '--version' || arg === '-v') {
      options.version = args[++i];
    } else if (arg === '--name' || arg === '-n') {
      options.packageName = args[++i];
    } else if (arg === '--arch') {
      options.architecture = args[++i];
    } else if (arg === '--maintainer') {
      options.maintainer = args[++i];
    } else if (arg === '--description') {
      options.description = args[++i];
    } else if (arg === '--section') {
      options.section = args[++i];
    } else if (arg === '--priority') {
      options.priority = args[++i];
    } else if (arg === '--license') {
      options.license = args[++i];
    } else if (arg === '--on-install-error') {
      const strategy = args[++i];
      if (strategy === 'stop' || strategy === 'rollback') {
        options.onInstallError = strategy;
      }
    } else if (!arg.startsWith('-') && !options.dir) {
      options.dir = arg;
    }
    
    i++;
  }
  
  return options;
}

export async function runBuildCommand(args) {
  const parsedArgs = args || process.argv.slice(2);
  const options = parseArgs(parsedArgs);
  
  if (options.help) {
    showBuildHelp();
    process.exit(0);
  }

  if (!options.dir) {
    logger.error('Error: Please specify a directory to build from.');
    console.log('\nUsage:\n  debcompose build <dir> [options]\n  debcompose <dir> [options]\n\nUse --help for more options.\n');
    process.exit(1);
  }

  try {
    const files = await fs.readdir(options.dir);
    const debFiles = files.filter(f => f.endsWith('.deb'));
    
    if (debFiles.length === 0) {
      logger.error(`No .deb files found in directory: ${options.dir}`);
      process.exit(1);
    }

    const result = await buildBundle({
      debDir: options.dir,
      outputDir: options.outputDir,
      version: options.version,
      package: options.packageName,
      architecture: options.architecture,
      maintainer: options.maintainer,
      description: options.description,
      section: options.section,
      priority: options.priority,
      license: options.license,
      onInstallError: options.onInstallError,
    });
    
    logger.info(`Bundle created: ${result.outputPath}`);
  } catch (e) {
    logger.error('Build Error:', e.message || e);
    process.exit(1);
  }
}

export async function runServeCommand(_args) {
  const { startServer } = await import('./server.js');
  startServer();
}

const commandHandlers = {
  serve: runServeCommand,
  server: runServeCommand,
  build: runBuildCommand,
};

const DEFAULT_COMMAND = 'build';

async function handleCommand(command, userArgs) {
  const handler = commandHandlers[command];
  if (handler) {
    await handler(userArgs);
    return;
  }
  
  if (!command.startsWith('-')) {
    userArgs.unshift(DEFAULT_COMMAND);
    await runBuildCommand(userArgs);
    return;
  }
  
  logger.error('Unknown command:', command);
  process.exit(1);
}

async function main() {
  const userArgs = process.argv.slice(2);
  
  if (userArgs.length === 0) {
    showGlobalHelp();
    process.exit(0);
    return;
  }
  
  const firstArg = userArgs[0];
  
  if (firstArg === 'help' || firstArg === '--help' || firstArg === '-h') {
    showGlobalHelp();
    process.exit(0);
    return;
  }
  
  await handleCommand(firstArg, userArgs);
}

main().catch((err) => {
  logger.error('Fatal:', err);
  process.exit(1);
});
