#!/usr/bin/env node

import { parseArgs } from 'node:util';
import { mkdir } from 'node:fs/promises';
import { join } from 'node:path';
import { ConsoleLogger } from './logger/index.js';
import { generateManifest, writeManifest } from './manifest/index.js';
import { writeControl } from './control/index.js';
import { writePostinst, writePostrm } from './scripts/index.js';
import { buildBundle } from './builder/index.js';

const logger = new ConsoleLogger('info');

async function main() {
  const args = process.argv.slice(2);

  if (args.length === 0) {
    showHelp();
    return;
  }

  const [command, ...rest] = args;

  if (command === '--help' || command === '-h') {
    showHelp();
    return;
  }

  if (command === '--version' || command === '-V') {
    logger.info('debcompose v0.1.0');
    return;
  }

  try {
    switch (command) {
      case 'build':
        await handleBuild(rest);
        break;

      case 'generate':
        await handleGenerate(rest);
        break;

      case 'manifest':
        await handleManifest(rest);
        break;

      default:
        logger.error(`unknown command: ${command}`);
        process.exitCode = 1;
        break;
    }
  } catch (err) {
    logger.error(err);
    process.exitCode = 1;
  }
}

function showHelp() {
  logger.info('debcompose — Deb Package Bundle Builder');
  logger.info('');
  logger.info('Usage:');
  logger.info('  debcompose build <deb-dir> [options]');
  logger.info('  debcompose manifest generate <deb-dir> [output-dir] [version]');
  logger.info('  debcompose generate debian <deb-dir> [output-dir]');
  logger.info('');
  logger.info('Build options:');
  logger.info('  --output, -o        Output directory (default: current dir)');
  logger.info('  --version, -v       Bundle version (default: 1.0.0)');
  logger.info('  --name, -n          Package name');
  logger.info('  --arch              Architecture (default: amd64)');
  logger.info('  --maintainer        Package maintainer');
  logger.info('  --description       Package description');
  logger.info('  --verbose           Enable debug logging');
  logger.info('');
  logger.info('Examples:');
  logger.info('  debcompose build ./packages --output ./dist --version 2.0.0');
}

async function handleBuild(args) {
  const { values, positionals } = parseArgs({
    args,
    allowPositionals: true,
    options: {
      output: { type: 'string', short: 'o' },
      version: { type: 'string', short: 'v' },
      name: { type: 'string', short: 'n' },
      arch: { type: 'string', default: 'amd64' },
      maintainer: { type: 'string' },
      description: { type: 'string' },
      verbose: { type: 'boolean', default: false },
    },
  });

  if (values.verbose) {
    logger.level = 'debug';
  }

  const [debDir] = positionals;

  if (!debDir) {
    logger.error('Usage: debcompose build <deb-dir> [options]');
    process.exitCode = 1;
    return;
  }

  const result = await buildBundle({
    debDir,
    outputDir: values.output,
    version: values.version,
    package: values.name,
    architecture: values.arch,
    maintainer: values.maintainer,
    description: values.description,
  });

  logger.info(`bundle built: ${result.outputPath}`);
  logger.info(`packages: ${result.manifest.packages.length}`);
}

async function handleGenerate(args) {
  const [subcommand, ...rest] = args;

  switch (subcommand) {
    case 'debian': {
      const [debDir, outputDir] = rest;
      if (!debDir) {
        logger.error('Usage: debcompose generate debian <deb-dir> [output-dir]');
        process.exitCode = 1;
        return;
      }

      const manifest = await generateManifest(debDir, '1.0.0');
      const outDir = outputDir || debDir;

      const debianDir = join(outDir, 'DEBIAN');
      await mkdir(debianDir, { recursive: true });

      await writeControl(debianDir, {
        package: manifest.packages[0]?.name || 'bundle-installer',
        version: manifest.version,
        architecture: 'amd64',
        maintainer: 'Unknown <unknown>',
        description: 'Bundle installer\n Auto-generated by debcompose.',
      });

      await writePostinst(debianDir, manifest);
      await writePostrm(debianDir, manifest);

      logger.info(`DEBIAN directory generated: ${debianDir}`);
      break;
    }
    default:
      logger.error(`unknown generate subcommand: ${subcommand}`);
      process.exitCode = 1;
      break;
  }
}

async function handleManifest(args) {
  const [subcommand, ...rest] = args;

  switch (subcommand) {
    case 'generate': {
      const [debDir, outputDir, version] = rest;
      if (!debDir) {
        logger.error('Usage: debcompose manifest generate <deb-dir> [output-dir] [version]');
        process.exitCode = 1;
        return;
      }
      const manifest = await generateManifest(debDir, version || '1.0.0');
      const outDir = outputDir || debDir;
      await writeManifest(manifest, outDir);
      logger.info(`manifest generated: ${outDir}/manifest.json`);
      break;
    }
    default:
      logger.error(`unknown manifest subcommand: ${subcommand}`);
      process.exitCode = 1;
      break;
  }
}

main();
