import express from "express";
import multer from "multer";
import path from "node:path";
import fs from "node:fs/promises";
import crypto from "node:crypto";
import { open } from 'node:fs/promises';
import { BundleBuilder } from "./services/BundleBuilder.js";
import { ConsoleLogger } from "./logger/index.js";

const port = process.env.DEB_COMPOSE_PORT || 3000;
const logger = new ConsoleLogger(process.env.DEB_COMPOSE_LOG_LEVEL || "info");
const bundleBuilder = new BundleBuilder();
const app = express();

const buildStatuses = new Map();
const BUILD_STATUS_TTL = 5 * 60 * 1000; // 5 minutes
const MAX_BUILD_STATUSES = 1000;

function scheduleBuildCleanup(buildId) {
  setTimeout(() => {
    const entry = buildStatuses.get(buildId);
    if (entry && (entry.status === 'completed' || entry.status === 'failed')) {
      buildStatuses.delete(buildId);
      logger.debug(`Evicted build status: ${buildId}`);
    }
  }, BUILD_STATUS_TTL);
}

function addBuildStatus(buildId, entry) {
  // Evict oldest entry if at capacity
  if (buildStatuses.size >= MAX_BUILD_STATUSES) {
    const oldestKey = buildStatuses.keys().next().value;
    buildStatuses.delete(oldestKey);
    logger.debug(`Evicted oldest build status: ${oldestKey}`);
  }
  buildStatuses.set(buildId, entry);
}

// Read environment variables for default configuration
const envConfig = {
  version: process.env.DEB_COMPOSE_VERSION || "1.0.0",
  name: process.env.DEB_COMPOSE_NAME || null,
  arch: process.env.DEB_COMPOSE_ARCH || "amd64",
  maintainer: process.env.DEB_COMPOSE_MAINTAINER || "Unknown <unknown>",
  description:
    process.env.DEB_COMPOSE_DESCRIPTION ||
    "Bundle installer\n Auto-generated by debcompose.",
  section: process.env.DEB_COMPOSE_SECTION || "misc",
  priority: process.env.DEB_COMPOSE_PRIORITY || "optional",
  license: process.env.DEB_COMPOSE_LICENSE || "",
};

// Request logging middleware
app.use((req, res, next) => {
  logger.info(`${req.method} ${req.url}`);
  next();
});

const storage = multer.diskStorage({
  destination: async (req, file, cb) => {
    const sessionId = req.body?.sessionId || 'default';
    const dir = path.join('uploads', sessionId);
    try {
      await fs.mkdir(dir, { recursive: true });
      cb(null, dir);
    } catch (err) {
      cb(err);
    }
  },
  filename: (req, file, cb) => {
    // Strip path separators to prevent filename injection
    const safeName = path.basename(file.originalname);
    const uniqueName = crypto.randomBytes(8).toString('hex') + '_' + safeName;
    cb(null, uniqueName);
  },
});

const upload = multer({
  storage,
  limits: {
    fileSize: 500 * 1024 * 1024, // 500MB per file
    files: 5, // max 5 files per session
  },
  fileFilter: (req, file, cb) => {
    if (file.originalname.endsWith(".deb")) {
      cb(null, true);
    } else {
      cb(new Error("Only .deb files are allowed"));
    }
  },
});

// Deb files are ar archives starting with the magic bytes !<arch>\n
const DEB_MAGIC = Buffer.from('!<arch>\n');

async function isValidDebFile(filePath) {
  try {
    const handle = await open(filePath, 'r');
    try {
      const buf = Buffer.alloc(8);
      const { bytesRead } = await handle.read(buf, 0, 8, 0);
      return bytesRead >= 8 && buf.slice(0, 7).equals(DEB_MAGIC);
    } finally {
      await handle.close();
    }
  } catch {
    return false;
  }
}

app.use(express.json());
app.use(express.static("src/public"));

// Endpoint to get default configuration from environment variables
app.get("/api/config/defaults", (req, res) => {
  res.json(envConfig);
});

app.post("/api/bundles/preview", async (req, res) => {
  const { packages, order, config, sessionId } = req.body;

  if (!packages || !order) {
    return res.status(400).json({ error: "Missing packages or order" });
  }

  const effectiveSessionId = sessionId || 'default';
  const uploadDir = path.join("uploads", effectiveSessionId);

  try {
    await fs.access(uploadDir);
  } catch {
    return res.status(400).json({ error: "Upload directory not found, please upload packages first" });
  }

  const previewPackages = [];
  let hasMissingFiles = false;
  for (const pkg of order) {
    const pkgInfo = packages.find((p) => p.name === pkg);
    if (pkgInfo?.path) {
      const fullPath = path.join("uploads", effectiveSessionId, pkgInfo.id || pkgInfo.path);
      try {
        await fs.access(fullPath);
        const stat = await fs.stat(fullPath);
        previewPackages.push({
          name: path.basename(pkgInfo.name || pkg, '.deb'),
          file: path.basename(fullPath),
          size: stat.size,
        });
      } catch {
        hasMissingFiles = true;
        previewPackages.push({
          name: path.basename(pkgInfo.name || pkg, '.deb'),
          file: path.basename(fullPath),
          error: 'file not found',
        });
      }
    }
  }

  const manifest = {
    version: config?.version || envConfig.version,
    packages: previewPackages,
  };

  const bundleDirName = config?.name || config?.package || envConfig.name || 'bundle';

  const structure = [
    { path: "DEBIAN/", type: "dir" },
    { path: "DEBIAN/control", type: "file", size: "auto-generated" },
    { path: "DEBIAN/postinst", type: "file", size: "auto-generated" },
    { path: "DEBIAN/postrm", type: "file", size: "auto-generated" },
    { path: "DEBIAN/md5sums", type: "file", size: "auto-generated" },
    { path: "opt/", type: "dir" },
    { path: `opt/${bundleDirName}/`, type: "dir" },
    ...previewPackages.map(p => ({ path: `opt/${bundleDirName}/${p.file}`, type: "file" })),
    { path: `opt/${bundleDirName}/manifest.json`, type: "file", size: "auto-generated" },
  ];

  res.json({
    manifest,
    structure,
    packages: previewPackages,
    config: {
      name: config?.name || envConfig.name,
      version: config?.version || envConfig.version,
      arch: config?.arch || envConfig.arch,
      maintainer: config?.maintainer || envConfig.maintainer,
      section: config?.section || envConfig.section,
      priority: config?.priority || envConfig.priority,
    },
    warning: hasMissingFiles ? 'Some uploaded files were not found on the server. Please re-upload.' : undefined,
  });
});

app.post("/api/packages/upload", upload.single("package"), async (req, res) => {
  if (!req.file) {
    logger.warn('Upload failed: no file provided');
    return res.status(400).json({ error: 'No file uploaded' });
  }

  // Validate deb magic bytes
  const valid = await isValidDebFile(req.file.path);
  if (!valid) {
    logger.warn(`Upload rejected: file is not a valid deb archive: ${req.file.originalname}`);
    await fs.unlink(req.file.path).catch(() => {});
    return res.status(400).json({ error: 'File is not a valid .deb package' });
  }

  logger.info(`File uploaded: ${req.file.originalname}`);
  res.json({
    message: 'File uploaded successfully',
    filename: req.file.filename,
    originalName: req.file.originalname,
  });
});

app.post("/api/bundles/generate", async (req, res) => {
  const { packages, order, config, sessionId } = req.body;

  if (!packages || !order) {
    logger.warn('Generate bundle failed: missing packages or order');
    return res.status(400).json({ error: "Missing packages or order" });
  }

  const effectiveSessionId = sessionId || 'default';
  const buildId = crypto.randomBytes(8).toString('hex');

  const statusEntry = {
    buildId,
    status: 'pending',
    progress: 0,
    error: null,
    bundleId: null,
    downloadUrl: null,
    createdAt: new Date().toISOString(),
    completedAt: null,
  };
  addBuildStatus(buildId, statusEntry);

  logger.info(`Queued bundle generation: ${buildId} (${packages.length} packages, session: ${effectiveSessionId})`);

  // Start build asynchronously
  (async () => {
    try {
      statusEntry.status = 'building';
      statusEntry.progress = 25;

      const result = await bundleBuilder.build({
        packages: packages.map((p) => ({
          name: p.name,
          path: path.join("uploads", effectiveSessionId, p.id),
        })),
        order,
        outputDir: "dist",
        config: {
          name: config?.name || envConfig.name,
          package: config?.name || envConfig.name,
          version: config?.version || envConfig.version,
          arch: config?.arch || envConfig.arch,
          architecture: config?.arch || envConfig.arch,
          maintainer: config?.maintainer || envConfig.maintainer,
          description: config?.description || envConfig.description,
          section: config?.section || envConfig.section,
          priority: config?.priority || envConfig.priority,
          license: config?.license || envConfig.license,
          onInstallError: config?.onInstallError || 'stop',
        },
      });

      statusEntry.progress = 75;

      if (!result.success) {
        statusEntry.status = 'failed';
        statusEntry.error = result.error;
        statusEntry.completedAt = new Date().toISOString();
        logger.error('Bundle generation failed:', result.error);
        scheduleBuildCleanup(buildId);
        return;
      }

      statusEntry.status = 'completed';
      statusEntry.progress = 100;
      statusEntry.bundleId = result.bundleId;
      statusEntry.downloadUrl = `/api/bundles/${result.bundleId}`;
      statusEntry.completedAt = new Date().toISOString();

      logger.info(`Bundle generated: ${result.bundleId}`);
      scheduleBuildCleanup(buildId);
    } catch (error) {
      statusEntry.status = 'failed';
      statusEntry.error = error.message || 'Unknown error';
      statusEntry.completedAt = new Date().toISOString();
      logger.error('Bundle generation error:', error);
      scheduleBuildCleanup(buildId);
    } finally {
      // Cleanup session upload directory recursively
      const sessionDir = path.join("uploads", effectiveSessionId);
      try {
        await fs.rm(sessionDir, { recursive: true, force: true });
        logger.debug(`Cleaned up session directory: ${sessionDir}`);
      } catch (e) {
        logger.warn(`Failed to clean up session directory: ${sessionDir}`, e.message);
      }
    }
  })();

  res.json({
    message: "Bundle generation queued",
    buildId,
    statusUrl: `/api/bundles/status/${buildId}`,
  });
});

app.get('/api/bundles/status/:buildId', (req, res) => {
  const { buildId } = req.params;
  const entry = buildStatuses.get(buildId);

  if (!entry) {
    return res.status(404).json({ error: 'Build not found', status: 'not_found' });
  }

  res.json({
    status: entry.status,
    progress: entry.progress,
    error: entry.error,
    bundleId: entry.bundleId,
    downloadUrl: entry.downloadUrl,
    createdAt: entry.createdAt,
    completedAt: entry.completedAt,
  });
});

app.get("/api/bundles/:id", async (req, res) => {
  const { id } = req.params;
  const distPath = path.resolve("dist");
  const filePath = path.resolve(distPath, id);

  // Prevent path traversal — ensure the resolved path is within dist/
  if (!filePath.startsWith(distPath + path.sep)) {
    return res.status(404).json({ error: "Bundle not found" });
  }

  try {
    await fs.access(filePath);
    const stats = await fs.stat(filePath);
    if (!stats.isFile()) {
      return res.status(404).json({ error: "Bundle not found" });
    }
    res.download(filePath, async () => {
      await fs.unlink(filePath);
    });
  } catch {
    res.status(404).json({ error: "Bundle not found" });
  }
});

export function startServer(customPort) {
  const listenPort = customPort !== undefined ? customPort : port;
  const server = app.listen(listenPort, () => {
    logger.info(`DebCompose HTTP Server running at http://localhost:${server.address().port}`);
  });
  return server;
}
