import express from "express";
import multer from "multer";
import path from "node:path";
import fs from "node:fs/promises";
import crypto from "node:crypto";
import { BundleBuilder } from "./services/BundleBuilder.js";
import { ConsoleLogger } from "./logger/index.js";

const port = process.env.DEB_COMPOSE_PORT || 3000;
const logger = new ConsoleLogger(process.env.DEB_COMPOSE_LOG_LEVEL || "info");
const bundleBuilder = new BundleBuilder();
const app = express();

const buildStatuses = new Map();

// Read environment variables for default configuration
const envConfig = {
  version: process.env.DEB_COMPOSE_VERSION || "1.0.0",
  name: process.env.DEB_COMPOSE_NAME || null,
  arch: process.env.DEB_COMPOSE_ARCH || "amd64",
  maintainer: process.env.DEB_COMPOSE_MAINTAINER || "Unknown <unknown>",
  description:
    process.env.DEB_COMPOSE_DESCRIPTION ||
    "Bundle installer\n Auto-generated by debcompose.",
  section: process.env.DEB_COMPOSE_SECTION || "misc",
  priority: process.env.DEB_COMPOSE_PRIORITY || "optional",
  license: process.env.DEB_COMPOSE_LICENSE || "",
};

// Request logging middleware
app.use((req, res, next) => {
  logger.info(`${req.method} ${req.url}`);
  next();
});

const storage = multer.diskStorage({
  destination: async (req, file, cb) => {
    const sessionId = req.body?.sessionId || 'default';
    const dir = path.join('uploads', sessionId);
    try {
      await fs.mkdir(dir, { recursive: true });
      cb(null, dir);
    } catch (err) {
      cb(err);
    }
  },
  filename: (req, file, cb) => {
    const uniqueName = crypto.randomBytes(8).toString('hex') + '_' + file.originalname;
    cb(null, uniqueName);
  },
});

const upload = multer({
  storage,
  fileFilter: (req, file, cb) => {
    if (file.originalname.endsWith(".deb")) {
      cb(null, true);
    } else {
      cb(new Error("Only .deb files are allowed"));
    }
  },
});

app.use(express.json());
app.use(express.static("src/public"));

// Endpoint to get default configuration from environment variables
app.get("/api/config/defaults", (req, res) => {
  res.json(envConfig);
});

app.post("/api/packages/upload", upload.single("package"), async (req, res) => {
  if (!req.file) {
    logger.warn('Upload failed: no file provided');
    return res.status(400).json({ error: 'No file uploaded' });
  }
  logger.info(`File uploaded: ${req.file.originalname}`);
  res.json({
    message: 'File uploaded successfully',
    filename: req.file.filename,
    originalName: req.file.originalname,
  });
});

app.post("/api/bundles/generate", async (req, res) => {
  const { packages, order, config, sessionId } = req.body;

  if (!packages || !order) {
    logger.warn('Generate bundle failed: missing packages or order');
    return res.status(400).json({ error: "Missing packages or order" });
  }

  const effectiveSessionId = sessionId || 'default';
  const buildId = crypto.randomBytes(8).toString('hex');

  const statusEntry = {
    buildId,
    status: 'pending',
    progress: 0,
    error: null,
    bundleId: null,
    downloadUrl: null,
    createdAt: new Date().toISOString(),
    completedAt: null,
  };
  buildStatuses.set(buildId, statusEntry);

  logger.info(`Queued bundle generation: ${buildId} (${packages.length} packages, session: ${effectiveSessionId})`);

  // Start build asynchronously
  (async () => {
    try {
      statusEntry.status = 'building';
      statusEntry.progress = 25;

      const result = await bundleBuilder.build({
        packages: packages.map((p) => ({
          name: p.name,
          path: path.join("uploads", effectiveSessionId, p.id),
        })),
        order,
        outputDir: "dist",
        version: config?.version || envConfig.version,
        package: config?.name || envConfig.name,
        architecture: config?.arch || envConfig.arch,
        maintainer: config?.maintainer || envConfig.maintainer,
        description: config?.description || envConfig.description,
        section: config?.section || envConfig.section,
        priority: config?.priority || envConfig.priority,
        license: config?.license || envConfig.license,
      });

      statusEntry.progress = 75;

      if (!result.success) {
        statusEntry.status = 'failed';
        statusEntry.error = result.error;
        logger.error('Bundle generation failed:', result.error);
        return;
      }

      statusEntry.status = 'completed';
      statusEntry.progress = 100;
      statusEntry.bundleId = result.bundleId;
      statusEntry.downloadUrl = `/api/bundles/${result.bundleId}`;
      statusEntry.completedAt = new Date().toISOString();

      logger.info(`Bundle generated: ${result.bundleId}`);
    } catch (error) {
      statusEntry.status = 'failed';
      statusEntry.error = error.message || 'Unknown error';
      logger.error('Bundle generation error:', error);
    } finally {
      // Cleanup session upload directory recursively
      const sessionDir = path.join("uploads", effectiveSessionId);
      try {
        await fs.rm(sessionDir, { recursive: true, force: true });
        logger.debug(`Cleaned up session directory: ${sessionDir}`);
      } catch (e) {
        logger.warn(`Failed to clean up session directory: ${sessionDir}`, e.message);
      }
    }
  })();

  res.json({
    message: "Bundle generation queued",
    buildId,
    statusUrl: `/api/bundles/status/${buildId}`,
  });
});

app.get('/api/bundles/status/:buildId', (req, res) => {
  const { buildId } = req.params;
  const entry = buildStatuses.get(buildId);

  if (!entry) {
    return res.status(404).json({ error: 'Build not found', status: 'not_found' });
  }

  res.json({
    status: entry.status,
    progress: entry.progress,
    error: entry.error,
    bundleId: entry.bundleId,
    downloadUrl: entry.downloadUrl,
    createdAt: entry.createdAt,
    completedAt: entry.completedAt,
  });
});

app.get("/api/bundles/:id", async (req, res) => {
  const { id } = req.params;
  const filePath = path.join("dist", id);
  try {
    await fs.access(filePath);
    res.download(filePath, async () => {
      await fs.unlink(filePath);
    });
  } catch {
    res.status(404).send("Bundle not found");
  }
});

export function startServer() {
  app.listen(port, () => {
    logger.info(`DebCompose HTTP Server running at http://localhost:${port}`);
  });
}
