import express from "express";
import multer from "multer";
import path from "node:path";
import fs from "node:fs/promises";
import { BundleBuilder } from "./services/BundleBuilder.js";

const port = process.env.DEB_COMPOSE_PORT || 3000;
const bundleBuilder = new BundleBuilder();
const app = express();

// Read environment variables for default configuration
const envConfig = {
  version: process.env.DEB_COMPOSE_VERSION || "1.0.0",
  name: process.env.DEB_COMPOSE_NAME || null,
  arch: process.env.DEB_COMPOSE_ARCH || "amd64",
  maintainer: process.env.DEB_COMPOSE_MAINTAINER || "Unknown <unknown>",
  description:
    process.env.DEB_COMPOSE_DESCRIPTION ||
    "Bundle installer\n Auto-generated by debcompose.",
  section: process.env.DEB_COMPOSE_SECTION || "misc",
  priority: process.env.DEB_COMPOSE_PRIORITY || "optional",
  license: process.env.DEB_COMPOSE_LICENSE || "",
};

const upload = multer({
  dest: "uploads/",
  fileFilter: (req, file, cb) => {
    if (file.originalname.endsWith(".deb")) {
      cb(null, true);
    } else {
      cb(new Error("Only .deb files are allowed"));
    }
  },
});

app.use(express.json());
app.use(express.static("src/public"));

// Endpoint to get default configuration from environment variables
app.get("/api/config/defaults", (req, res) => {
  res.json(envConfig);
});

app.post("/api/packages/upload", upload.single("package"), async (req, res) => {
  if (!req.file) return res.status(400).json({ error: "No file uploaded" });
  res.json({
    message: "File uploaded successfully",
    filename: req.file.filename,
    originalName: req.file.originalname,
  });
});

app.post("/api/bundles/generate", async (req, res) => {
  const { packages, order, config } = req.body;

  if (!packages || !order) {
    return res.status(400).json({ error: "Missing packages or order" });
  }

  try {
    const result = await bundleBuilder.build({
      packages: packages.map((p) => ({
        name: p.name,
        path: path.join("uploads", p.id),
      })),
      order,
      outputDir: "dist",
      version: config?.version || envConfig.version,
      package: config?.name || envConfig.name,
      architecture: config?.arch || envConfig.arch,
      maintainer: config?.maintainer || envConfig.maintainer,
      description: config?.description || envConfig.description,
      section: config?.section || envConfig.section,
      priority: config?.priority || envConfig.priority,
      license: config?.license || envConfig.license,
    });

    if (!result.success) {
      return res.status(500).json({ error: result.error });
    }

    // Cleanup only the uploaded files that were used in this bundle
    const uploadPromises = packages.map(
      (p) => fs.unlink(path.join("uploads", p.id)).catch(() => {}), // Ignore if file already deleted
    );
    await Promise.all(uploadPromises);

    // Cleanup old bundles in dist
    const distFiles = await fs.readdir("dist");
    for (const file of distFiles) {
      if (file !== result.bundleId) {
        await fs.unlink(path.join("dist", file));
      }
    }

    res.json({
      message: "Bundle generated successfully",
      bundleId: result.bundleId,
      downloadUrl: `/api/bundles/${result.bundleId}`,
    });
  } catch (error) {
    res.status(500).json({ error: "Failed to generate bundle" });
  }
});

app.get("/api/bundles/:id", async (req, res) => {
  const { id } = req.params;
  const filePath = path.join("dist", id);
  try {
    await fs.access(filePath);
    res.download(filePath, async () => {
      await fs.unlink(filePath);
    });
  } catch {
    res.status(404).send("Bundle not found");
  }
});

export function startServer() {
  app.listen(port, () => {
    console.log(`DebCompose HTTP Server running at http://localhost:${port}`);
  });
}
